import { users } from '../../../../db/users';
import { events } from '../../../../db/events';
import type { PageServerLoad } from './$types';
import { ObjectId } from 'mongodb';
import { redirect } from "@sveltejs/kit";


export const actions = {

    JoinClass: async (event, params) => {
		
        const data = await event.request.formData();
		const name = data.get('name');
		const email = data.get('email');
		const picture = data.get('picture');

		let dataEvents = await events.find({_id: new ObjectId(event.params.slug) }).toArray();



		const quotaLeft = parseInt(dataEvents[0].quotaLeft) - 1;
		const attendance = parseInt(dataEvents[0].attendance) + 1;	
		let date = new Date().toLocaleString("es-CL", {timeZone: 'America/Santiago', hour12: false})
		const dia = date.substring(0, 5);
		const formattedDia = dia.replace("-", "/");
		const hora = date.substring(12, 17);
		const fullDate = formattedDia + " " + hora
		
		await events.updateOne(
			{ _id: new ObjectId(event.params.slug) },
			{
				$set:{
						quotaLeft: quotaLeft,
						attendance: attendance
				},
				$push: { 
						players: {nombre: name, fecha: fullDate, email: email, picture: picture, sortDate: new Date()}
					},
			}
		);	
		
		throw redirect (303, '/events/active/'+event.params.slug+'');
		
    },

	LeaveClass: async (event, params) => {
		
		const data = await event.request.formData();
		const name = data.get('name');
		const email = data.get('email');

		let dataEvents = await events.find({_id: new ObjectId(event.params.slug) }).toArray();

		const quotaLeft = parseInt(dataEvents[0].quotaLeft) + 1;
		const attendance = parseInt(dataEvents[0].attendance) - 1;	

		await events.updateOne(
			{ _id: new ObjectId(event.params.slug) },
			{ 
				$pull: { 'players': { email: email } },
				$set:{
					quotaLeft: quotaLeft,
					attendance: attendance	
				}
			}
		);	
		
		throw redirect (303, '/events/active/'+event.params.slug+'');
		
    }
};

export const load: PageServerLoad = async function({ params, cookies, locals }) {
	
	if (!locals.user) {
		throw redirect(302, "/")
		
	}

	const localsData = locals.user
	let joined = false;
	let joinedWaitlist = false;
	let dataUser = await users.find({ _id: localsData.email }).toArray();

	let dataEvents = await events.find({_id: new ObjectId(params.slug) }).toArray();
	// Formatting Date and Hour
	
	dataEvents[0].fecha = dataEvents[0].date.toLocaleString("es-CL", {timeZone: 'America/Santiago', hour12: false}).split(',')[0].replaceAll("-", "/");
	dataEvents[0].hora = dataEvents[0].date.toLocaleString("es-CL", {timeZone: 'America/Santiago', hour12: false}).split(',')[1].slice(1, -3);	

	// Typecasts autogenerated object _id to string
	dataEvents[0]._id = dataEvents[0]._id.toString()
	

	// Sort players by joined Date
	const sortedPlayers = dataEvents[0].players.sort(
		(objA, objB) => Number(objA.sortDate) - Number(objB.sortDate),
	  );

	// Replace with sorted dict
	dataEvents[0].players = sortedPlayers
	
	// Check if player joined main list
	if (dataEvents[0].players.length >= 1) {
		for (let index = 0; index <= dataEvents[0].players.length; index++){
		
			// Check with email
			try {
				if (dataEvents[0].players[index].email == localsData.email) {
					joined = true;
					break
				}
			} catch (error) {
				joined = false;
			}
				
		} 

	} else {
		joined = false;
	}
		
	return{
			user: dataUser,
			events: dataEvents,
			joined: joined,
			joinedWaitlist: joinedWaitlist,
			localsData: localsData
	}
}

