import { matches } from '../../../db/matches';
import type { PageServerLoad } from './$types';
import { redirect } from "@sveltejs/kit";
import { error } from "@sveltejs/kit";


export const load: PageServerLoad = async function({cookies, locals, request}) {

	if (!locals.user) {
		throw redirect(302, "/")
		
	}

	let dataMatches = await matches.find({date: {$gte: new Date()}}).sort({date: 1}).toArray();

	// Formatting Date and Hour
	for (let index = 0; index < dataMatches.length; index++) {
		dataMatches[index].fecha = dataMatches[index].date.toLocaleString("es-CL", {timeZone: 'America/Santiago', hour12: false}).split(',')[0].replaceAll("-", "/");
		dataMatches[index].hora = dataMatches[index].date.toLocaleString("es-CL", {timeZone: 'America/Santiago', hour12: false}).split(',')[1].slice(1, -3);

		// Typecasts autogenerated object _id to string
		dataMatches[index]._id = dataMatches[index]._id.toString()
	}
	
	return{
			matches: dataMatches
	}
}