import { users } from '../../../db/users';
import { trainings } from '../../../db/trainings';
import type { PageServerLoad } from './$types';
import { redirect } from "@sveltejs/kit";


export const load: PageServerLoad = async function({cookies, locals, request}) {

	//Secure route after jwt is generated
	console.log(cookies.get("jwt"));
	

	let dataTrainings = await trainings.find({date: {$gte: new Date()}}).sort({date: 1}).toArray();

	// Formatting Date and Hour
	for (let index = 0; index < dataTrainings.length; index++) {
		dataTrainings[index].fecha = dataTrainings[index].date.toLocaleString().split(',')[0].slice(0);
		dataTrainings[index].hora = dataTrainings[index].date.toLocaleString().split(',')[1].slice(1, -3);

		// Typecasts autogenerated object _id to string
		dataTrainings[index]._id = dataTrainings[index]._id.toString()
	}

	return{
			trainings: dataTrainings
	}
}