import { users } from '../../../db/users';
import { trainings } from '../../../db/trainings';
import type { PageServerLoad } from './$types';
import { redirect } from "@sveltejs/kit";

export const load: PageServerLoad = async function({locals}) {
	if (!locals.user) {
		throw redirect(302, "/")
		
	}
	let dataTrainings = await trainings.find({date: {$lt: new Date()}}).sort({date: -1}).toArray();
	console.log(dataTrainings);	

	// Formatting Date and Hour
	for (let index = 0; index < dataTrainings.length; index++) {
		dataTrainings[index].fecha = dataTrainings[index].date.toLocaleString().split(',')[0].slice(0);
		dataTrainings[index].hora = dataTrainings[index].date.toLocaleString().split(',')[1].slice(1, -3);

		// Typecasts autogenerated object _id to string
		dataTrainings[index]._id = dataTrainings[index]._id.toString()
	}

	return{
			trainings: dataTrainings
	}
}