import { users } from '../../../db/users';
import { trainings } from '../../../db/trainings';
import type { PageServerLoad } from './$types';
import { redirect } from "@sveltejs/kit";

export const load: PageServerLoad = async function({locals}) {

	if (!locals.user) {
		throw redirect(302, "/")
		
	}
	
	let dataTrainings = await trainings.find({date: {$lt: new Date()}}).sort({date: -1}).toArray();

	// Formatting Date and Hour
	for (let index = 0; index < dataTrainings.length; index++) {
		dataTrainings[index].fecha = dataTrainings[index].date.toLocaleString("es-CL", {timeZone: 'America/Santiago'}).split(',')[0].replaceAll("-", "/");
		dataTrainings[index].hora = dataTrainings[index].date.toLocaleString("es-CL", {timeZone: 'America/Santiago'}).split(',')[1].slice(1, -3);
		// Typecasts autogenerated object _id to string
		dataTrainings[index]._id = dataTrainings[index]._id.toString()
	}	
	
	return{
			trainings: dataTrainings
	}
}