import { users } from '../../../../db/users';
import { events } from '../../../../db/events';
import type { PageServerLoad } from './$types';
import { ObjectId } from 'mongodb';
import { redirect } from "@sveltejs/kit";


export const load: PageServerLoad = async function({ params, locals }) {
	if (!locals.user) {
		throw redirect(302, "/")
		
	}

	const localsData = locals.user
	let joined = false;
	let dataUser = await users.find({ _id: localsData.email }).toArray();
	
	let dataEvents = await events.find({_id: new ObjectId(params.slug) }).toArray();
	// Formatting Date and Hour
	
	dataEvents[0].fecha = dataEvents[0].date.toLocaleString("es-CL", {timeZone: 'America/Santiago', hour12: false}).split(',')[0].replaceAll("-", "/");
	dataEvents[0].hora = dataEvents[0].date.toLocaleString("es-CL", {timeZone: 'America/Santiago', hour12: false}).split(',')[1].slice(1, -3);

	// Typecasts autogenerated object _id to string
	dataEvents[0]._id = dataEvents[0]._id.toString()

	// Sort players by joined Date
	const sortedPlayers = dataEvents[0].players.sort(
		(objA, objB) => Number(objA.sortDate) - Number(objB.sortDate),
	  );

	// Replace with sorted dict
	dataEvents[0].players = sortedPlayers

	// Check if player joined main list
	if (dataEvents[0].players.length >= 1) {
		for (let index = 0; index <= dataEvents[0].players.length; index++){
		
			// Check with email
			try {
				if (dataEvents[0].players[index].email == localsData.email) {
					joined = true;
					break
				}
			} catch (error) {
				joined = false;
			}
				
		} 

	} else {
		joined = false;
	}
	
	return{
		user: dataUser,
		events: dataEvents,
		joined: joined,
		localsData: localsData
	}
}
