import { events } from '../../../db/events';
import type { PageServerLoad } from './$types';
import { redirect } from "@sveltejs/kit";
import { error } from "@sveltejs/kit";


export const load: PageServerLoad = async function({cookies, locals, request}) {

	if (!locals.user) {
		throw redirect(302, "/")
		
	}

	let dataEvents = await events.find({date: {$gte: new Date()}}).sort({date: 1}).toArray();

	// Formatting Date and Hour
	for (let index = 0; index < dataEvents.length; index++) {
		dataEvents[index].fecha = dataEvents[index].date.toLocaleString("es-CL", {timeZone: 'America/Santiago'}).split(',')[0].replaceAll("-", "/");
		dataEvents[index].hora = dataEvents[index].date.toLocaleString("es-CL", {timeZone: 'America/Santiago'}).split(',')[1].slice(1, -3);

		// Typecasts autogenerated object _id to string
		dataEvents[index]._id = dataEvents[index]._id.toString()
	}
	
	return{
			events: dataEvents
	}
}